/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
}

repositories {
    // Use the plugin portal to apply community plugins in convention plugins.
    gradlePluginPortal()
}

// should be same as 'buildSrc/src/main/kotlin/Versions.kt'
object Versions {
    const val springBoot = "3.0.5"
    const val dependencyManagementPlugin = "1.1.0"
    const val checkstyle = "8.41.1"
    const val kotlin = "1.8.10"
}

dependencies {
    implementation("org.springframework.boot:spring-boot-gradle-plugin:${Versions.springBoot}")
    implementation("io.spring.gradle:dependency-management-plugin:${Versions.dependencyManagementPlugin}")
}
