name: Java Code Style Check

on:
  pull_request:
    branches:
      - master

jobs:
  checkstyle:
    name: Checkstyle Run
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: download checkstyle
        run: curl -o checkstyle.jar -L https://github.com/checkstyle/checkstyle/releases/download/checkstyle-8.41.1/checkstyle-8.41.1-all.jar
      - name: checkstyle
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          java -jar checkstyle.jar -c checkstyle-config.xml -f xml . | reviewdog -f=checkstyle -name="Checkstyle Check" -reporter=github-pr-check
          java -jar checkstyle.jar -c checkstyle-config.xml -f xml . | reviewdog -f=checkstyle -name="Checkstyle Comment" -reporter=github-pr-review