name: CI

on:
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/setup-java@v1
        with:
         java-version: 1.8
         architecture: x64

      - uses: actions/checkout@v2
        with:
          repository: SDUOJ/sduoj-server

      - name: Cache sduoj-server interface
        id: cache-sduoj-server-interface
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/*.java') }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install if cache not hit
        if: steps.cache-sduoj-server-interface.outputs.cache-hit != 'true'
        run: |
          chmod +x ./mvnw
          ./mvnw install \
              --projects sduoj-submit/sduoj-submit-interface \
              --projects sduoj-problem/sduoj-problem-interface \
              --projects sduoj-filesys/sduoj-filesys-interface \
              --also-make \
              --no-transfer-progress \
              --batch-mode \
              -Dmaven.test.skip=true \

      - uses: actions/checkout@v2
      - run: |
          chmod +x ./gradlew
          ./gradlew build
