name: Compilation

on:
  pull_request:
    branches: 
      - master
  workflow_dispatch: # add manually button

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/setup-java@v1
        with:
         java-version: 1.8
         architecture: x64

      - uses: actions/checkout@v2
        with:
          repository: SDUOJ/sduoj-server

      - name: Cache sduoj-server interface
        id: cache-sduoj-server-interface
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/*.java') }}-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-m2-${{ hashFiles('**/*.java') }}-${{ hashFiles('**/*.gradle.kts') }}

      - name: PublishToMavenLocal if not hit cache
        if: steps.cache-sduoj-server-interface.outputs.cache-hit != 'true'
        run: |
          chmod +x ./gradlew
          ./gradlew publishToMavenLocal

      - uses: actions/checkout@v2

      - run: |
          chmod +x ./gradlew
          ./gradlew build
