name: Compilation

on:
  pull_request:
    branches: 
      - master
  workflow_dispatch: # add manually button

jobs:
  compilation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: adopt-hotspot
          architecture: x64

      - uses: actions/checkout@v2
        with:
          repository: SDUOJ/sduoj-server

      - name: Cache sduoj-server interface
        id: cache-sduoj-server-interface
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2
            ~/.gradle
          key: ${{ runner.os }}-m2-${{ hashFiles('**/*.java') }}-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-m2-${{ hashFiles('**/*.java') }}-${{ hashFiles('**/*.gradle*') }}

      - name: PublishToMavenLocal if not hit cache
        if: steps.cache-sduoj-server-interface.outputs.cache-hit != 'true'
        run: |
          chmod +x ./gradlew
          ./gradlew publishToMavenLocal -x test

      - uses: actions/checkout@v2

      - name: Gradle Build
        run: |
          chmod +x ./gradlew
          ./gradlew build --scan
