name: Compilation

on:
  pull_request:
    branches: 
      - master
  workflow_dispatch: # add manually button

jobs:
  compilation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Run Gradle
        uses: gradle/gradle-build-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          arguments: |
            build
            --scan

      - name: To disable the cache of sduoj-server packages
        run: rm -rfv ~/.gradle/caches/modules*/**/cn.edu.sdu.qd.oj*/**
