name: Compilation

on:
  pull_request:
    branches: 
      - master
  workflow_dispatch: # add manually button

jobs:
  compilation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: adopt-hotspot
          architecture: x64
          cache: gradle

      - name: To disable the cache of sduoj-server packages
        run: |
          rm -rf ~/.gradle/caches/modules**/files**/cn.edu.sdu.qd.oj**
          rm -rf ~/.gradle/caches/modules**/metadata**/descriptors/cn.edu.sdu.qd.oj**

      - name: Gradle Build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          chmod +x ./gradlew
          ./gradlew build --scan
