name: Compilation

on:
  pull_request:
    branches: 
      - master
  workflow_dispatch: # add manual trigger button

jobs:
  compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run Gradle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gradlew build --scan

      - name: To disable the cache of sduoj-server packages
        run: rm -rfv ~/.gradle/caches/modules*/**/com.sduoj*/**
